index.html, src/Compiler.elm
Elixir uses `#` not `%%`, this fixes that. 
Also it would be cool to support [doc comments in Elixir.](https://hexdocs.pm/elixir/master/writing-documentation.html)
=> fix comments

Main.elm, elixir-stuff/elmchemy/lib/elmchemy.ex, elixir-stuff/elmchemy/lib/glue.ex, elixir-stuff/elmchemy/lib/test.ex, elixir-stuff/elmchemy/test/elmchemy_test.exs, src/Compiler.elm, src/elixir_std/MyList.elm, tests/Tests.elm, tests/elm-package.json
=> Tuples, records, record updates, record types, 20 new test cases

elixir-stuff/elmchemy/lib/elmchemy.ex, elixir-stuff/elmchemy/lib/glue.ex, elixir-stuff/elmchemy/test/elmchemy_test.exs, src/Compiler.elm, src/Example.elm
=> Nicer curry

example/index.js, src/Compiler.elm, src/ExAlias.elm, src/ExContext.elm, src/ExExpression.elm, src/ExStatement.elm, src/ExType.elm, src/Helpers.elm, stable/index.js, tests/Tests.elm
=> types substitution

.travis.yml
=> Reduce Travis time

elixir-stuff/elmchemy/lib/XBasics.ex, elixir-stuff/elmchemy/lib/XKernel.ex, elixir-stuff/elmchemy/lib/XList.ex, src/Compiler.elm, src/ElixirStd/XBasics.elm, src/ExContext.elm, src/ExExpression.elm, src/ExStatement.elm, src/Helpers.elm
=> Support for different comment types

README.md
=> Add mix integration guide

src/ExExpression.elm, tests/Tests.elm
=> operators as functions w/o Elmchemy

src/Compiler.elm, src/ExContext.elm, src/ExStatement.elm
```elm
a : Int -> Int
a b = 1
```
->
```elixir
@spec a(integer) :: integer
@spec a :: (integer -> integer)
curry a/1
def a(b) do
1
end 
```
---------------------------------------------------
```elm
{- flag nospec:a -}
a : Int -> Int
a b = 1
```
->
```elixir
curry a/1
def a(b) do
1
end 
```
=> flags working

elixir-stuff/elmchemy/lib/XBasics.ex, elixir-stuff/elmchemy/lib/XKernel.ex, elixir-stuff/elmchemy/lib/XList.ex, elixir-stuff/elmchemy/lib/XTuple.ex, elm-package.json, src/ElixirStd/XTuple.elm, src/ExExpression.elm, src/ExStatement.elm, tests/elm-package.json, tests/run-tests.sh
Closes: #64 
Closes: #52 
Closes: #50 
I've added basic support for functions binding in `let...in` block. It will bind to anonymous function without curring for now.
=> Upgrade elm-ast to 4.0

elmchemy
Example project before:
Example project now:
=> Closes #99 - optimized compiler

Makefile, src/ExAlias.elm, src/ExExpression.elm, src/ExReserved.elm, src/ExStatement.elm, src/ExType.elm, src/Helpers.elm
=> Operators and reserved keywords

Makefile, elmchemy
=> #136 and #134 Copy ex files and distringuish compiled from dependencies

src/ExStatement.elm
Reverts wende/elchemy#133
Closes #147
=> Revert "Closes #129 native available"

src/ExExpression.elm, src/ExStatement.elm, src/ExType.elm
=> Closes #137 XSet

elchemy, example/index.js, src/ExAlias.elm, src/ExContext.elm, src/ExStatement.elm
Closes #161 
NO MORE WARNINGS DURING COMPILATION
=> Typedocs before types instead of docs

src/Compiler.elm, src/ExAlias.elm, src/ExContext.elm, src/ExExpression.elm, src/ExFfi.elm, src/ExFunction.elm, src/ExOperator.elm, src/ExStatement.elm, src/ExType.elm, src/ExVariable.elm, src/Helpers.elm, tests/Tests.elm
Closes #185 
Closes #173 
Closes #174
=> [WIP] Documentation and code quality

bump.sh, upload-github-release-asset.sh
=> Closes #195 auto upload

elchemy_ex/elm-package.json, elm-package.json, src/ExExpression.elm, src/ExVariable.elm, tests/Tests.elm, tests/elm-package.json
=> Closes #220 cross referrence let in

.travis.yml, Makefile, elchemy, src/ExContext.elm, src/ExExpression.elm, src/ExOperator.elm, src/ExStatement.elm, src/ExType.elm, src/Helpers.elm, tests/Tests.elm
=> Closes #184 short type aliases

src/ExFfi.elm, src/ExFunction.elm
=> Closes #218 - Delambdify functions when calling from outside

src/ExExpression.elm, tests/Tests.elm
=> Closes #225 - Union types aren't functions

README.md
=> Closes #241 -  Update README.md

src/ExFunction.elm, src/ExOperator.elm, src/ExStatement.elm
=> Closes #247 overloaded clause as

elchemy
=> Closes #246 - snake case directory trees

src/ExAlias.elm, src/ExExpression.elm, src/ExType.elm, src/Helpers.elm, tests/Tests.elm
=> Closes #251 - Non-import type aliases from other modules (Module.Type a) resolve correctly

.travis.yml, Makefile, src/ExContext.elm, src/ExExpression.elm
=> 253 error on nested cases

elchemy, elchemy_node.js, src/Compiler.elm, templates/elchemy.exs
=> Huge compilation time improvement (16s down to 0.1 s)

templates/Hello.elm
=> Closes #268 - Moduledoc for the example

elchemy, lib/mix/tasks/compile.elchemy.ex, src/Compiler.elm, templates/Hello.elm
=> Closes #270 bugfix type aliases recompilation

.travis.yml, Makefile, elchemy_ex/elm-package.json, src/Compiler.elm, src/ExContext.elm, src/ExExpression.elm, src/ExFunction.elm, src/ExStatement.elm, tests/Tests.elm
=> Closes #272 nested case fix

roadmap/BASIC_TYPES.md, roadmap/COMMENTS.md, roadmap/FUNCTIONS.md, roadmap/INTEROP.md, roadmap/MODULES.md, roadmap/README.md, roadmap/STRUCTURES.md, roadmap/TYPES.md, roadmap/TYPE_ALIASES.md
=> Closes #257 roadmap

elchemy
=> Closes #284 non english systems date bug

src/Compiler.elm
=> Closes #290 - incremental compiler bug 

src/ExExpression.elm, tests/Tests.elm
=> Closes #292 - Functions in resolved type aliases no longer miss parens

Makefile, lib/mix/tasks/compile.elchemy.ex
=> Closes #299 format when > 1.6.0

.gitignore, roadmap/INTEROP.md, roadmap/SUMMARY.md
=> Closes #313 Fixes interop in gitbook and new gitbbok

elchemy
=> Bug: Closes #327

templates/elchemy.exs
=> Closes #338 - No project name

elchemy
=> Closes #340 - Bug: Clean makes init not able to work

.travis.yml, Main.elm, Makefile, elchemy, src/Elchemy/Alias.elm, src/Elchemy/Compiler.elm, src/Elchemy/Context.elm, src/Elchemy/Expression.elm, src/Elchemy/Ffi.elm, src/Elchemy/Function.elm, src/Elchemy/Statement.elm, src/Elchemy/Type.elm, tests/Tests.elm
=> Closes #348 Prepare for elm 0.19

.tool-versions, mix.exs, package.json, src/Elchemy/Compiler.elm
=> Closes #360 elixir 1.7.4 ffi support
